### ISSUE TITLE
Content import does not strip newlines in content titles

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-library#11]
Apparently, some of the content contains newlines in the title. While this does not affect the display inside the file list, it does affect changing to that folder.

**Comment by afaikafk** [comment]
Fixed in Outernet-Project/librarian-content@3114a6423879c4efb69aea03ff5d79ed2d96a83a

**Comment by foxbunny** [comment]
I'm reopening this until we have a confirmation that the regexp would support valid non-English names.

**Comment by afaikafk** [comment]
Can we close this now?

**Comment by foxbunny** [comment]
Closing for now. Until it comes back and bites us in the behind.
