### ISSUE TITLE
Keyword links do not handle whitespace appropriately

### ISSUE THREAD

**Issue by ben-en** [Outernet-Project/librarian-library#12]
When clicking on a keyword link to filter by a keyword that contains whitespace, the whitespace is replaced with `%2520` instead of `%20`, resulting in a search for `%20keyword`.

Results are similar when a keyword is separated by a space. For instance `Instructional Books` is incorrectly written as `Instructional%2520Books` in the URL bar and `Instructional%20Books` in the search bar and result message.

Expected behavior with `Instructional Books` is `Instructional%20Books` in the URL bar and `Instructional Books` in the search bar and result message.

![20151029_160943](https://cloud.githubusercontent.com/assets/11149483/10834551/7bd6b1a8-7e57-11e5-8373-22e0814b5ca3.png)

**Comment by afaikafk** [comment]
Fixed in 5853d3317f6ffa208ead55cc2ecbfaa4ace32be6
