### ISSUE TITLE
Import step in setup wizard does not successfully import content

### ISSUE THREAD

**Issue by ben-en** [Outernet-Project/librarian-library#14]
StR:
1. With outernet-rx-1.4.201 firmware, injest some content
2. Flash new outernet-rx-1.4.202 firmware
3. Observe import step in setup wizard
4. Choose "keep" and complete setup wizard
5. Observe empty library and no `Old content` dir
6. Restart FSAL and refresh the files view
7. Observe `Old content` dir

**Comment by afaikafk** [comment]
Fixed in 167f69fda972651e18e4e72e0f2aeeff50c93c24
