### ISSUE TITLE
UI language description is misleading

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-library#7]
The description suggests that users will be able to change the default language at some later time:

> This will be the starting user inteface language for all users. Users will be able to change it later.

Users will only be able to change their own language, and this should be clearer.

For example: "Users will be able to choose their preferred interface language later."

**Comment by ben-en** [comment]
Proposed string:

Please select the default interface language. This will be the default user inteface language for all users. Users will be able to change their own language later.
